name: rfam-github-actions-pipeline

on: [push]

jobs:
  rfam-connect:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: Rfam
      DB_USER: rfamro
      DB_PORT: 4497
      DB_HOST: mysql-rfam-public.ebi.ac.uk

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to Public Rfam Database
        run: |
          mysql -u $DB_USER -h $DB_HOST -P $DB_PORT -D $DB_DATABASE < script.sql
